name: Test 
on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
jobs:
  test-package:
    if: ${{ contains(github.event.head_commit.message, 'test') && !contains(github.event.head_commit.message, 'release')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: cd packages/korkscript && npm install --save-dev && npm run build
      - name: Testing
        run: node packages/korkscript/src/bin/ksc examples